openapi: 3.1.0
info:
  title: Products Module
  version: 1.0.0
paths:
  /api/products:
    get:
      summary: Get all products
      tags:
        - Products
      security:
        - bearerAuth: []
      parameters:
        - name: page
          in: query
          schema:
            type: integer
            default: 1
        - name: limit
          in: query
          schema:
            type: integer
            default: 10
        - name: search
          in: query
          schema:
            type: string
      responses:
        '200':
          description: Berhasil mengambil daftar produk

    post:
      summary: Create product baru (ADMIN)
      tags:
        - Products
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [name, sku, categoryId, locationId]
              properties:
                name:
                  type: string
                  example: "Mouse Wireless"
                sku:
                  type: string
                  example: "MS-WRL-001"
                stock:
                  type: integer
                  default: 0
                minimumStock:
                  type: integer
                  default: 10
                categoryId:
                  type: string
                  format: uuid
                locationId:
                  type: string
                  format: uuid
      responses:
        '201':
          description: Produk berhasil dibuat

  /api/products/{id}/stock:
    get:
      summary: Get product stock info
      tags:
        - Products
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Berhasil mengambil informasi stok produk